import React from 'react'

const Term = () => {
  return (
    <div>
      <h1 className='text-danger'>welcome to the Term and Condition</h1><br/><br/>
      
      <h4>I. Defined Terms:</h4>
Unless otherwise specified, the capitalized words shall have the meanings as defined herein below:

Agreement” Shall mean and include the completed application form, its attachment(s) and the terms and conditions stated herein. It shall deemed to have been executed at New Delhi.<br/>
“Date of Commencement: Is the date indicating the acceptance of the application by the user to the service. It shall be specified by the company in it s notice to the user either through e-mail or conventional mail.<br/>
“Date of Termination”: Is the date of expiry mentioned in the notice or/and the letter of termination.<br/>
“My Subscriptions”: Contains time to time information and description of the Services for the User provided by the Company in writing or contained in the website<br/>
“Registration Data”: Is the database of all the particulars and information supplied by the User on initial application and subscription, including but without limiting to the User' s name, telephone number, mailing address, account and email address.<br/>
Words referring to masculine include the feminine and the singular include the plural and vice versa as the context admits or requires; and Words importing persons includes individuals, bodies corporate and unincorporated.<br/>
“Services”: Means the Services to be provided by the Company to the User of NanuBhaiProperty.com and shall include the provision of following facilities:<br/>
Service to the Users wishing to post their profile or listing for the purpose of sale/rental of their property, and for users providing property services etc..<br/>
Service to the Users who wishes to secure a property through NanuBhaiProperty.com and its Internet links.<br/>
Service to the Users who wishes to insert advertisements at NanuBhaiProperty.com.<br/>
<br/>Service to the Users who wishes to receive advertisements and promotional messages on www.NanuBhaiProperty.com and through emails.<br/>
“NanuBhaiProperty.com ”: Is defined as the Internet web site of the Company at www.NanuBhaiProperty.com
”User": Is defined as an individual or corporate subscriber for the Services and the signatory, whose particulars are contained in the application form and includes his successors and permitted assignees<br/>
<h4>II. Commencement of Service</h4>
The Service shall be deemed to have commenced on the Date of Commencement of service.
<br/><h4>III. Subscription Fees</h4><br/>
The applicable rate of the Subscription Fees for the Service provided shall be such as mentioned in the “My Subscriptions” page or as may be prescribed by the Company from time to time
Liability for the Subscription Fees shall accrue from the Date of Commencement.
All individual Users who access or make postings of information at NanuBhaiProperty.com for the purpose of buying property shall be exempted from the application of this clause.<br/>
<br/><h4>IV. Payment</h4><br/>
Where Subscription Fees accrues it shall be payable at or within such time as stated in the invoice(s) issued by the Company to the User.<br/>
The Subscription Fees shall be paid by the User on demand. In case the user disputes the same for any reason whatsoever, he shall make the payment towards the Subscription Fees accrued subject to the decision of the Company on the dispute. In the event of Company’s deciding the dispute in the User’s favour, the Company shall refund to the User any excess amount paid by the User free of interest.<br/>
Any delay in the payment by the User of any sums due under this Agreement, the Company shall have the right to charge interest on the outstanding amount from the date the payment became due until the date of final payment by the User.
<br/><h4>V. Cancellation</h4><br/>
NanuBhaiProperty.com shall reserve the exclusive right to cancel any content whatsoever from being published or reflected on its website or in any other mode. The cancellation charges payable to the User shall be at the applicable rates laid down in the cancellation and refund policy.<br/>
<br/><h4>VI. Obligations of User/Subscriber</h4><br/>
The accuracy of the Registration Data given to the Company on initial application for the Service shall be the sole responsibility of the User.<br/>
Any licenses, permits, consents, approvals and intellectual property or other rights as may be required for using the Service shall be obtained by the User at his own cost.<br/>
The User will ensure compliance with all notices or instructions given by the Company from time to time to enable the use of the Service.
The User understands and agrees that User is responsible for all applicable taxes and for all costs that are incurred in using the NanuBhaiProperty.com service.<br/>
<br/>The User shall be solely responsible for all information retrieved, stored and transmitted through the Service by him.
The User shall keep confidential and not disclose to any person the User's password and user identification and all activities and transmission performed by the User through his user identification.<br/>
The User shall immediately notify the Company of any un-authorized use of the User's account or any other breach of security known to the User.<br/>
The User shall promptly make the payment to the Company towards the Subscription Fees as and when it becomes payable.<br/>
The User shall be responsible for the set-up or configuration of his equipment for access to the Service.<br/>
NanuBhaiProperty.com in its sole discretion shall reserve the right to edit, modify and alter the content. User agrees that the online advertisements placed with NanuBhaiProperty.com shall be reflected after 48 hours. The user further agrees to the stipulated 48 hours processing.<br/>
<br/>The User will indemnify Nanu Bhai Property for any action or claim committed/made by any third party resulting from any information posted on the site by the user or/and anybody else on his behalf.<br/>
“Nanu Bhai Property do not accept any responsibility towards the data entered in our website. The user who has entered the data is fully responsible for any wrong data entered and be liable for any and all action taken by third party (whether civil/criminal). Nanu Bhai Property however shall Endeavour to use the best industry practice of weeding out all wrong data/ false data entered and undertakes to withdraw all such data within 24 hours of receipt of such complaint. All complaint should be addresses by email at support@nanubhaiproperty.com“
“The user agrees that any data entered into herein can and shall be saved, used and commercially exploited by Nanu Bhai Property as deemed fit by them”.<br/>
“User of the website agrees to indemnify and keep Nanu Bhai Property indemnified from any wrong/false data entered into and hereby warrants and covenants that all data entered into the website is true and correct and belongs exclusively to him and not to any other third party”
<br/><h4>VII. Prohibited Actions</h4><br/>
User is restrained from allowing any person other than the authorized person(s) named in the application form to use the Service
The User undertakes not to resell or assign his/her rights or obligations under these Terms & Conditions. User also agrees not to make any unauthorized commercial use of the Service.
The User shall use the Service only for the purpose for which it is subscribed.
The User shall comply with all applicable laws (and shall not contravene any applicable law) of India relating to the Services, including any regulation made pursuant thereto.<br/>
The User shall not to print, download, duplicate or otherwise copy, delete, vary or amend or use any data or personal information posted by any User on NanuBhaiProperty.com except such data and information which is posted by the particular User himself.<br/>
The User shall not share the Service with any person without the prior written approval of the Company.
The User shall not use the Service for any unlawful purpose including without limitation criminal purposes.<br/>
The Service shall not be used to send or receive any message, which is offensive on moral, religious, racial or political grounds or of an abusive, indecent, obscene, defamatory or menacing nature.
The User shall be prohibited if they persistently send messages or make postings on NanuBhaiProperty.com to any other User or third party who access NanuBhaiProperty.com without reasonable cause or for causing any threat or/and harassment or/and annoyance or/and anxiety or/and any other inconvenience whatsoever caused to any person.
The User shall not infringe on any intellectual property rights of any person or/and retain information in any computer system or otherwise with an intention to do so.<br/>
The User shall give out to the company a non-exclusive, worldwide, royalty-free, irrevocable, sub-license able (through multiple tiers) right to exercise all copyright and publicity rights, in any existing or future media, known or unknown, over the material or User Data displayed in your listings. For the purpose of this Agreement, "User Data" shall mean all information (if any) submitted by the User to NanuBhaiProperty.com. "Individually Identifiable User Data" shall mean that subset of "User Data" which can be reasonably used to identify a specific individual such as their name, address, phone number, etc. The User Data shall be deemed to be the property of NanuBhaiProperty.com. The User shall take all reasonable efforts to ensure that it is accurate and complete and not misleading in any way.<br/>
<br/>User agrees not to make use of anyone else's Information other than as necessary to complete any transactions in which you are involved.
The User shall not violate, or attempt to violate the security of NanuBhaiProperty.com and/or any web sites linked to NanuBhaiProperty.com or gain un-authorized access any information regarded as private by other Users or persons, including but without limitation to accessing data and information not intended for them or logging onto a server or account which the User is not authorized to access, attempting to probe, scan or test the vulnerability of a system or network or attempting to breach security or authentication.
The User shall be prohibited to introduce, post or transmit any information or software, which contains a virus, worm or other harmful component into the internet or NanuBhaiProperty.com network system.<br/>
<br/>In the event that the User breaches any of the above mentioned covenants, the Company shall have the right to delete any material relating to the violations. The Company reserves the unilateral right to suspend or/and deactivate the User's access to NanuBhaiProperty.com the Service and/or any other related facility in case of violation of terms of use. In addition to the right to indemnity available to the Company, the Company shall have the right to any legal remedy, against the User to recover the loss suffered by the Company and the harm caused to the reputation of the Company, due to such violation by the User.
The Users shall avail the Service on NanuBhaiProperty.com or any other related site for lawful purposes alone. Transmission or/and distribution or/and storage of material or/and conduct in violation of any applicable local or/and state or/and Central or/and foreign law or/and regulation is prohibited. This includes without limitation any unauthorized use of material protected by patent or/and copyright or/and trademark or/and other intellectual property right, material that is obscene or/and defamatory or/and libellous or/and constitutes an illegal threat, or/and violates rights of privacy or publicity, or/and violates export control laws. The User may use the information on our site only to the extent necessary to facilitate the related transactions.
Company strongly opposes SPAM, which floods the Internet with unwanted and unsolicited email and deteriorates the performance and availability of the NanuBhaiProperty.com site. All forms of SPAM, or any other activities that have the effect of facilitating SPAM, are strictly prohibited.
Company also prohibits the use of another Internet service to send or post SPAM to drive visitors to your site hosted on or through NanuBhaiProperty.com site, whether or not the messages were originated by you, under your direction, or by or under the direction of a related or unrelated third party.
The User shall not host, display, upload, modify, publish, transmit, update or share any information on the NanuBhaiProperty.com site that
(a) belongs to another person and to which you do not have any right to;
(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
(c) harm minors in any way;
(d) infringes any patent, trademark, copyright or other proprietary rights;
(e) violates any law for the time being in force;
(f) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
(g) impersonate another person;
(h) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
(i) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
Any information uploaded by the User shall be subject to relevant laws and may disabled, or and may be subject to investigation under appropriate laws. Furthermore, if the User is found to be in non-compliance with the laws and regulations, these terms, or the privacy policy of NanuBhaiProperty.com, Company may terminate your account/block your access to NanuBhaiProperty.com and Company reserves the right to remove any non-compliant information uploaded by the User.
<br/><h4>VIII. Confidentiality & Security</h4><br/>
To protect the secrecy of his user Identification and/or password the User shall take all such measures as may be necessary (including but without limiting to changing his password from time to time and shall not reveal the same to any other person(s).
Since a user identification is necessary to access the Service; the User shall use only his own user Identification.
It is agreed by the User that he acquires no rights to any mailbox number or/and the user identification or/and circuit reference or/and any codes assigned to him by the Company. The User further agrees that except as otherwise proved herein, the Company reserves the right to change or/and re-assign the same to the User at its sole discretion without being liable to the User for any kind of damages or/and relief or/and any other consequence/s.
In the event of theft or/and loss of user identification or/and password or/and security word, the User shall notify the Company immediately by telephone or/and personally concurrently provide the Company with a written notice to that effect. The User shall remain liable for use of the Services by any third party until such theft or loss is notified to the Company.
The password and username being made available to the customer shall be used only by the organization named by the customer and the employee of the organization. The User shall take all necessary pre-cautions to prevent un-authorized access or/and leakage of username or/and password being provided by the Company to him.
The user shall not use any software to automatically download or/and extract either a complete or/and partial listing from NanuBhaiProperty.com database without prior consent from Nanu Bhai Property in writing.<br/>
<br/><h4>IX. Maintenance</h4><br/>
The Company may at its sole discretion and without assigning any reason whatsoever at any time deactivate or/and suspend the User’s access to NanuBhaiProperty.com and/or the Services (as the case may be) without notice to carry out system maintenance or/and upgrading or/and testing or/and repairs or/and other related work. Without prejudice to any other provisions of this Agreement, the Company shall not be liable for any loss or/and damage or/and costs or/and expense that the User may suffer or incur, and no fees or/and charges payable by the User to the Company shall be deducted or refunded or rebated, as a result of such deactivation or/and suspension.
<br/><h4>X. Termination</h4><br/>
Either party to this agreement may terminate this Agreement by giving prior notice of 30 days in writing.
It shall be on the discretion of the Company that the period of notice of 30 days may be waived or a shorter period of notice may be accepted in writing from the User.
However, the Company irrespective of clause 1 and 2 above may terminate this Agreement with immediate effect, without prior notice to the User and without assigning any reason/s whatsoever
(a) if in the opinion of the Company, the User has breached any of the terms and conditions of this agreement or/and,
(b) if, in the opinion of the Company or/and any regulatory authority, it is not in the public interest to continue providing the Service to the User for any reason or/and,
(c) if the User is declared a bankrupt or/and the User enters into any compromise or arrangement with its creditors and further without any prejudice to any/all other rights:

<br/><h4>XI. Liabilities upon Termination</h4><br/>
If the Agreement is terminated pursuant to clauses set out in XI above, without prejudice to any other remedies available to the Company, the User shall be liable for Subscription Fees payable until the Date of Termination.
The amounts due and payable to the Company by the User upon termination shall be payable within 30 days of the relevant Date of Termination.<br/>
<br/><h4>XII. Suspension of Service</h4><br/>
If any monies payable by the User to the Company are not paid on the due date, the Company may without prejudice to any other rights or remedies that may be available to it suspend the Service provided to the User.
When the Service subscribed for is suspended, it shall be deemed to be terminated. The date shall be such as stipulated by the Company and the User shall be liable for all the charges and fees incurred upto the date.
Upon subsequent payment by the User of such monies as demanded by the Company, the Company may at its discretion and subject to such terms as it deems proper, reconnect the Service.<br/>
<br/><h4>XIII. Moneyback Policy</h4><br/>
Moneyback can be initiated by a User, using the Feedback link on NanuBhaiProperty.com or by writing to support@nanubhaiproperty.com if the User is unsatisfied with the responses received against a Listing posted using the Moneyback Package provided by the Company.
For claiming any moneyback, there should be atleast one property posted using the package.
User shall be first offered an extension of duration for the Listing that was posted using Moneyback Package for Free, to evaluate the responses again.
If the user is still not satisfied with the responses offered after the duration is extended, Moneyback shall be initiated by the Company.
Moneyback can be initiated within the lifetime of the listing (i.e. 60 days from date of posting).
Moneyback can only be initiated against the same Order ID & Customer Name as mentioned during Order Booking.
Order Booking should be in the Client's name as the refund will be processed in the same name.
For orders that were paid through online payment modes, the refunds will be processed after deduction of charges incurred by the Payment Gateway.
Refunds will be processed within 30 business days from receipt & acceptance of all relevant documents.
XIV. Violation of Terms & Conditions
If the NanuBhaiProperty.com, in its sole discretion, determines that a violation of the Terms & Conditions has occurred, NanuBhaiProperty.com may pursue any of its legal remedies, including but not limited to the immediate deletion of any offending material from its site or/and cancellation of your account and/or the exclusion of any person(s) who may have violated any Terms & Conditions. NanuBhaiProperty.com could also pursue violators with claims that they have violated various criminal and/or civil law provisions as applicable under the relevant Acts/Rules, etc of the land. NanuBhaiProperty.com will cooperate with any investigation by any Central or/and State or/and local body or/and any court or/and tribunal having the competence to carry out the same. Such cooperation may be without notice to the User. If NanuBhaiProperty.com believes in its sole discretion that any advertisement or/and services may create liability for NanuBhaiProperty.com, NanuBhaiProperty.com may take any actions that it believes are prudent or necessary to minimize or/and eliminate its potential liability, including but not limited to, the release of User information. In sum, NanuBhaiProperty.com reserves the right to refuse service to anyone at any time, or/and to remove any listings or/and any advertisements for any reason, and without notice.
XV. Disclaimer
Disclaimer of Warranties: The User shall agree that use of the service is at the user's sole risk. The service is provided on an "as is" or/and on an "as available" basis. NanuBhaiProperty.com expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement.
The Company/NanuBhaiProperty.com makes no warranty that the service shall meet user's requirements, that the service shall be uninterrupted or/and timely or/and secure or/and error free; nor does NanuBhaiProperty.com make any warranty as to the results that may be obtained from the use of the service or as to the accuracy or reliability of any information obtained from the service. Cancellations and alterations shall be effected only on the receipt of application regarding the same in writing.
There are no express representations and warranties, whether express or implied, made by the Company regarding the accuracy and/or quality of any information transmitted and/or obtained through the use of the Services or NanuBhaiProperty.com.
NanuBhaiProperty.com will not be liable for any time difference arising between a message released through a gateway/ server ( provided to NanuBhaiProperty.com ) and such message finally reaching the End User from the concerned service provider.
The Company shall not be liable for any disclosure of information concerning the User’s account and/or particular s nor for any error and/or omissions and/or inaccuracy with regard to information so disclosed. In addition The Company shall further not be liable for any loss or damages sustained by reason of such disclosure, whether intentionally or inadvertently.
In case the there is any loss of information, caused due to any reason, whether as a result of any disruption of service, suspension and/or termination of the Service, the Company shall not be liable in any way for the same. Further the Company is not responsible for the accuracy, quality and/or contents of any information available, received and/or transmitted through this Service.
All information are accepted in good faith and NanuBhaiProperty.com accept no responsibility whatsoever regarding the bonafide of the user, nor can any interviews be granted or/and correspondence entered into regarding any advertisement published.
The User shall ensure that while using the Service, all prevailing and applicable laws, rules and regulations, directly or indirectly for the use of systems, service or equipment shall at all times, be strictly complied with by the User and the Company shall not be liable in any manner whatsoever for default of any nature regarding the same, by the User.
The Company does not warrant that NanuBhaiProperty.com or any of the web sites linked to NanuBhaiProperty.com be free of any operational hazards or errors nor that it will be free of any virus or/and worm or/and any other harmful components.
It is not the Company’s policy to exercise any kind of supervisory or editorial control over and/or edit and/or amend any data and/or contents of any e-mails and/or posting of any information that may be inserted or/and made available or transmitted to a third party in or through NanuBhaiProperty.com and the User acknowledges the same. The User acknowledges and agrees that the Company has absolute discretion to refuse and/or suspend or/and terminate and/or delete and/or amend any artwork, materials and/or information or/and content of any data and/or information or/and posting so as, in the sole opinion of the Company, to comply with the prevailing legal framework and/or moral obligations as placed on the Company and in order to avoid infringing any third party’s rights and/or any other rules and/or standards and/or codes of practices that may be applicable to the posting or NanuBhaiProperty.com and/or the internet.
NanuBhaiProperty.com is not involved in any transaction between any parties who are using our website. There are risks, which the User assumes when dealing with people who might be acting under false pretences and the same shall be borne by the User. The website is a venue only and do not screen or/and censor or/and otherwise control the listings offered to other Users, nor does NanuBhaiProperty.com screen or/and censor or/and otherwise control the Users of its service. NanuBhaiProperty.com cannot and does not control the behaviour of the participants on this site. We cannot control whether or not Users of NanuBhaiProperty.com will complete the transactions they describe on our site. It is extremely important that the user takes care throughout his dealings with other people, users on this site. NanuBhaiProperty.com does not accept or/and assume responsibility for the content or/and context of the user comment.
If there is any dispute between the Users/participants on this site, it is agreed upon by the Users/participants that NanuBhaiProperty.com has no obligation whatsoever to be involved in any such dispute/s. In the event that the user has a dispute with one or more User/s or/and participant/s, the User hereby undertakes not to make any claims or/and demands or/and damages (actual or/and consequential) of every kind or/and nature or/and known or/and unknown or/and suspected or/and unsuspected or/and disclosed or/and undisclosed, arising out of or/and in any way related to such disputes and/or our service against the company or/and their officers or/and employees or/and agents or/and successors.
The User understands and agrees that any information or/and material and/or goods or/and services obtained through this website is done at user's own discretion and risk and that user shall be solely responsible for any damage/s or/and cost or/and any other consequence/s resulting from any transaction.
No advice or or/any information, whether oral or/and written, obtained by the User from NanuBhaiProperty.com or/and through or/and from the service shall create any warranty not expressly stated herein.
In case a visitor to the portal is desirous of conducting a site visit of the property he/she is interested in, it shall be the sole liability and duty of the Advertiser to arrange for such site visits. The Company/NanuBhaiProperty.com shall not be liable in any manner whatsoever, towards any liability and/or costs, arising out of such site visits including but not limited to non-fulfillment by the Advertiser in this regard.
The website’s total liability under this Agreement in any circumstance shall be limited to the total amount of fees or/and charges paid by the User to the Company’s website or the period immediately preceding two (2) months prior to the incident giving rise to the relevant claim.
This Website/ E-mail are vulnerable to data corruption, interception, tampering, viruses as well as delivery errors and we do not accept liability for any consequence that may arise therefrom
XVI. Limitation of Liability
User agrees that neither NanuBhaiProperty.com nor its group companies, directors, officers or employee shall be liable for any direct or/and indirect or/and incidental or/and special or/and consequential or/and exemplary damages, resulting from the use or/and the inability to use the service or/and for cost of procurement of substitute goods or/and services or resulting from any goods or/and data or/and information or/and services purchased or/and obtained or/and messages received or/and transactions entered into through or/and from the service or/and resulting from unauthorized access to or/and alteration of user's transmissions or/and data or/and arising from any other matter relating to the service, including but not limited to, damages for loss of profits or/and use or/and data or other intangible, even if NanuBhaiProperty.com has been advised of the possibility of such damages. User further agrees that NanuBhaiProperty.com shall not be liable for any damages arising from interruption, suspension or termination of service, including but not limited to direct or/and indirect or/and incidental or/and special consequential or/and exemplary damages, whether such interruption or/and suspension or/and termination was justified or not, negligent or intentional, inadvertent or advertent. User agrees that NanuBhaiProperty.com shall not be responsible or liable to user, or anyone, for the statements or conduct of any third party of the service. In sum, in no event shall Company's total liability to the User for all damages or/and losses or/and causes of action exceed the amount paid by the User to NanuBhaiProperty.com, if any, that is related to the cause of action.
The Company takes no responsibility/liability whatsoever for shortage or non fulfillment of the service/s on NanuBhaiProperty.com or any other related site due to or arising out of technical failure or/and malfunctioning or/and otherwise and the User hereby undertakes that in such situation/s, the User shall not claim any right/damages/ relief, etc against the Company for “Deficiency of service” under The Consumer Protection Act or any other Act/Rules, etc.
Nanu Bhai Property shall not be liable for any and all costs, charges, expenses, etc incurred in relation to the downloading fees by third party, airtime, ISP connection costs, etc., of which are to be borne by the user personally.
XVII. Use of Information/Data Supplied
The User hereby agrees and irrevocably authorizes that the Company has the right to:

Use for the company’s own purpose, any data or/and information supplied by the User in connection with this Agreement, and/or pass on such information to any other associated companies or selected third parties.
Retain all data or/and information supplied by the User while using the Service to remain at NanuBhaiProperty.com for the exclusive use of the Company in accordance with service agreement with the user, notwithstanding any termination of the Agreement or suspension of the Service to the User herein. Anything contrary to the above, unless specifically put down in writing, following the termination or suspension of the Service to the User, all such data and information shall remain in the Company’s property, records and databases as the exclusive property of the Company, for all times to come.
"By entering mobile number on NanuBhaiProperty.com while registering for an account or receiving alerts, contacting a property seller/buyer, user gives consent to Company and its partners/vendors and sub-partners/sub-vendors to send alerts, contact details, promotional SMS and promotional calls to the mobile number entered by the user, irrespective of whether the same is on the DNC list or any other such data base. In case user does not want to receive these messages on his/her mobile number, he/she shall not submit his/her mobile number with NanuBhaiProperty.com."
XVIII. Indemnity
User will defend, or at its option and settle any third party lawsuit or proceeding brought against the Company based upon or otherwise any claim arising from the fact that the User Content, Site and/or User features infringe any copyright, trade secret or trademark of such third party and second, the Company’s use of any User Content, provided that such use complies with the requirements of the Agreement and third, the User’s use of the Services in any manner inconsistent with or in breach of the Agreement; and/or fourth, any claim alleging facts that would constitute a breach of User’s representations and warranties made in this Agreement. Any such claim/proceeding if made directly on the User shall promptly be communicated to the Company by the User with all reasonable information, assistance and cooperation in defending the lawsuit or proceeding. The User shall give the Company full control and sole authority over the defense and settlement of such claim. The User may join in defense with counsel of its choice at its own expense subject to the approval of the company. The User unilaterally agree to indemnify and hold harmless, without objection, the Company, its officers, directors, employees and agents from and against any claims, actions and/or demands and/or liabilities and/or losses and/or damages whatsoever arising from or resulting from their use of NanuBhaiProperty.com or their breach of the terms of this Agreement. Indemnification shall be provided for any claim which shall arise and shall be limited to payment by the indemnifying party (“User”) of all damages and costs finally awarded for such claim, or settlement costs approved in writing by the Indemnitor (Company).
XIX. Confidentiality
For the purpose of this Agreement and attachments thereto and all renewals, “ Confidential Information ” means all financial, commercial, technical, operational, staff, management and other information, data and know-how relating to the Project or to a party (the “ Disclosing Party ” herein the Company ) or any other members of the Disclosing Party’s group of companies ( including, without limitation, as to products and services, assets, customers, date and database, suppliers or employees), which may be supplied to or may otherwise come into the possession of the other (the “ Receiving Party ”, herein the User ), whether orally or in writing or in any other form, and which is confidential or proprietary in nature or otherwise expressed by the Disclosing Party or by any of its Associates to be confidential, and not generally available to the public.
The Receiving Party shall keep confidential and secret and not disclose to any third party the Confidential Information nor any part of it, except to any of the Receiving Party’s Associates, if required and upon prior permission in writing from the Disclosing Party. The Receiving Party agrees to take all possible precautions with regard to protecting confidential information from any third party and shall ensure that all its Associates to whom such disclosure is made will act in accordance with the terms of this Agreement as if each of them were a party to this Agreement, and if required obtain a written statement from each of its employees/associates having access to such Proprietary Information undertaking to abide by the confidentiality conditions. All Proprietary Information shall be kept separate and exclusive and at the usual place of business (or residence as the case may be) of the Receiving Party.
Further no use, reproduction, transformation or storage of the Proprietary Information shall be made by the User without the prior written permission of the Company, except where required to be disclosed pursuant to any applicable law or legal process issued by any court or the rules of any competent regulatory body.
On request of the Disclosing Party made at any time, including at the time of termination of this Agreement, the Receiving Party shall deliver back to the Disclosing Party all original documents, records, data and other material in the possession, custody or control of the Receiving Party that bear or incorporate any part of the Proprietary Information. The obligations of confidentiality set out in this Agreement shall continue to be in force notwithstanding termination of this Agreement for any reason whatsoever.
All information and data submitted by the User shall become the property of the Company. However all such information shall be kept strictly confidential and the Company shall not, subject to “Violation of Terms & Conditions” clause, release any such data and information to any third party without the prior consent of the User.
The User has access to only his own data and information stored in the database at NanuBhaiProperty.com (subject to prior confirmation of identity) and nothing more. The User may edit or amend such data and information from time to time.
All confidential information (including name, e-mail address etc.) voluntarily revealed by the User in chat and bulletin board areas, is done at the sole discretion and risk of the User. If such information, collected by a third party is misused or results in unsolicited messages from such third parties, then such actions are beyond the use beyond the control and liability of Company and the company accepts no responsibility or liability whatsoever for such actions.
All copyright and/or know-how and/or any other related intellectual property rights to the Service or NanuBhaiProperty.com shall become and remain the sole and exclusive property of the Company and the User shall have no claims to the same. In the event the User has contributed any content to NanuBhaiProperty.com in any manner whatsoever, all intellectual property rights to the same shall become the absolute property of the Company, including all intellectual property rights and the User shall have no right or claim over the same, in any manner whatsoever. In the event that the User during the term of his Agreement or any time thereafter, uses such intellectual property in any other website or related activity, the same shall be considered as an infringement of the intellectual property rights of the Company and the Company shall have the right to take recourse to whatever legal remedial action is required, in the given facts and circumstances, the costs and peril of which will lie at the end of the User.
XX. Variation
The right to amend vary or change the terms and conditions contained herein and in the Services Guide at any time exclusively rests with the Company, upon notice (in such form as may be determined by the Company) to the User.
This Agreement will be periodically undated and the Terms and Conditions changed from time to time and the changed or updated Agreement posted at NanuBhaiProperty.com. The User should visit the site periodically to review the latest Terms and Conditions. For the avoidance of doubt, the User's continued use of the Service constitutes an affirmation and acknowledgement of the amended terms and conditions.
<br/><h4>XXI.</h4>
<br/> Discontinuation or Modification to Services
The Company reserves the unilateral right to add to /and/or change and/or delete and/or end the Service at anytime with or without notice to the User. Except for paid service, a pro-rated refund shall be effected for the remaining unused period.
There shall be no liability on behalf of the Company to the User or any third party in case the Company exercises its unilateral right to modify or discontinue the Service.
<br/><h4>XXII. Notices</h4><br/>
All notices shall be in English and in writing and (a) if sent to the User to the address identified on the Application Form and (b) if sent to the Company to such address as provided in writing for such notice purposes; provided, however, that all invoices and payments shall be sent to the attention of The Company’s Finance department, all legal notices shall be sent to the attention of the Company’s Legal Department, and all other correspondence shall be sent to the attention of the account manager specified by the Company. Notice shall be deemed given upon receipt when delivered personally and upon received acknowledgment / written verification of receipt from overnight courier and finally upon verification of receipt of registered or certified mail. All notices from the Company including notice of change to these Terms & Conditions or other matters related to NanuBhaiProperty.com will be done by displaying notices to Users on the service.
In the event User has any grievance in relation to any information uploaded on NanuBhaiProperty.com User may contact our Grievance Officer at support@nanubhaiproperty.com ;

We request you to please provide the following information in your complaint:-

(a) A physical or electronic signature of a person authorized to act on behalf of the copyright owner for the purposes of the complaint
(b) Identification of the copyrighted work claimed to have been infringed.
(c) Identification of the material on our website that is claimed to be infringing or to be the subject of infringing activity.
(d) The address, telephone number or e-mail address of the complaining party.
(e) A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law.
(f) A statement, under penalty of perjury, that the information in the notice of copyright infringement is accurate, and that the complaining party is authorized to act on behalf of the owner of the right that is allegedly infringed.
<br/><h4>XXIII. Non-exclusive Remedy</h4><br/>
Termination or expiration of this Agreement, in part or in whole, shall not limit either party from pursuing other remedies available to it, nor shall either party be relieved of its obligation to pay all fees that are due and owing under this Agreement through the effective date of termination. Neither party shall be liable to the other for any damages resulting solely from termination as permitted herein.
<br/><h4>XXIV. Waiver</h4><br></br>
The failure of NanuBhaiProperty.com to exercise or enforce any right or provision of these Terms & Conditions shall not constitute a waiver of such right or provision. If any provision of these Terms & Conditions is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of these Terms & Conditions shall remain in full force and effect.
<br/><h4>XXV. Entire Agreement</h4><br/>
This Agreement shall constitute the complete and exclusive agreement between the parties with respect to the subject matter hereof, superseding any prior agreements, documents and or communications regarding such subject matter. This Agreement may only be modified, or/and any rights under it waived, by a written document executed by the Company only. The right to change vary or amend, however exclusively rests with the Company.
XXVI. Governing Law and Jurisdiction
It is clarified that there is no agency or/and partnership or/and joint venture or/and employee-employer or/and franchiser-franchisee relationship between NanuBhaiProperty.com and any User of the Service.
The User agrees that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Terms & Conditions must be filed within 30 days after such claim or cause of action arose or be forever barred.
All information of whatsoever nature received from the user is in good faith and is bonafide. The information is believed to be true/ correct and complies with the laws of the land.
This Agreement and any dispute or matter arising from incidental use of NanuBhaiProperty.com is governed by the laws of India and the User and NanuBhaiProperty.com hereby submit to the exclusive jurisdiction of the courts at Delhi, India without regard to its conflict of law provisions.
      
    </div>
  )
}

export default Term
